qick fix
bcye/whathaveiread pull request #32
Opened 2018-10-29 12:52 UTC by sulochanaviji

good

2018-10-29 18:16 UTC, raysarebest requested changes

2018-10-29 18:16 UTC, raysarebest commented on .gitignore
> +# Pods/
```suggestion
Pods/
```

Some of our pods haven't been updated for Swift 4.2 yet, and we've made those fixes ourselves directly in this repository while we investigate other options, so we're committing our `Pods` directory for now

2018-10-29 18:16 UTC, raysarebest commented on WHIR/ViewControllers/TableViewController.swift
> +        } else {
The `else` block here is empty. Do we really need it?

2018-10-29 18:16 UTC, raysarebest commented on WHIR/Views/sv.lproj/About.strings
> +"lpw-Ku-zCI.text" = "Handgjord av © 2018 Bruce Röttgers och flera andra på GitHub\n\nLogo av Zlatko Najdenovski på Flaticon. Licensierad enligt Flaticon Basic License (https://www.flaticon.com/author
I translated this string into Swedish, and it's currently in `master`. What happened to it?

2018-11-01 00:04 UTC, bcye requested changes
I don't understand what you did. Can you please explain what you're trying to resolve with your pull request

2018-11-02 21:04 UTC, closed without merging